CREATE DATABASE DB_2DSI3_EVENTO;

USE DB_2DSI3_EVENTO;

CREATE TABLE TB_ADMINISTRADOR(
CD_ADMINISTRADOR INT AUTO_INCREMENT,
NM_ADMINISTRADOR VARCHAR(45) NOT NULL,
NM_EMAIL VARCHAR(100) NOT NULL,
CD_SENHA VARCHAR(15) NOT NULL,
PRIMARY KEY(CD_ADMINISTRADOR),
CONSTRAINT EMAIL_ADMIN_UNICO UNIQUE(NM_EMAIL)
);

ALTER TABLE TB_ADMINISTRADOR ADD COLUMN 
(ST_ADMINISTRADOR CHAR(1) NOT NULL DEFAULT 'T');

INSERT INTO TB_ADMINISTRADOR SET 
NM_ADMINISTRADOR = 'claudio', 
NM_EMAIL = 'claudio@mail.com', 
CD_SENHA = '1234';

update tb_administrador set ST_ADMINISTRADOR = 't' where CD_ADMINISTRADOR = 1;

select * from tb_administrador;

CREATE TABLE TB_PATROCINADOR(
CD_PATROCINADOR INT AUTO_INCREMENT,
NM_PATROCINADOR VARCHAR(45) NOT NULL,
DS_PATROCINADOR LONGTEXT,
IMG_PATROCINADOR VARCHAR(200),
ID_ADMINISTRADOR INT NOT NULL,
PRIMARY KEY(CD_PATROCINADOR),
CONSTRAINT ADM_PAT_FK
FOREIGN KEY(ID_ADMINISTRADOR) REFERENCES 
TB_ADMINISTRADOR(CD_ADMINISTRADOR)
ON UPDATE CASCADE
ON DELETE CASCADE
);

CREATE TABLE TB_ORGANIZADOR(
CD_ORGANIZADOR INT AUTO_INCREMENT,
NM_ORGANIZADOR VARCHAR(45) NOT NULL,
DS_ORGANIZADOR LONGTEXT,
IMG_ORGANIZADOR VARCHAR(200),
ID_ADMINISTRADOR INT NOT NULL,
PRIMARY KEY(CD_ORGANIZADOR),
CONSTRAINT ADM_ORG_FK 
FOREIGN KEY(ID_ADMINISTRADOR) REFERENCES
TB_ADMINISTRADOR(CD_ADMINISTRADOR)
ON UPDATE CASCADE
ON DELETE CASCADE
);

CREATE TABLE TB_USUARIO(
CD_USUARIO INT AUTO_INCREMENT,
NM_USUARIO VARCHAR(45) NOT NULL,
NM_EMAIL VARCHAR(100) NOT NULL,
CD_SENHA VARCHAR(15) NOT NULL,
DT_NASCIMENTO DATE NOT NULL,
CD_CPF VARCHAR(11) NOT NULL,
CD_RG VARCHAR(9) NOT NULL,
DT_CADASTRO TIMESTAMP NOT NULL 
DEFAULT CURRENT_TIMESTAMP
ON UPDATE CURRENT_TIMESTAMP,
PRIMARY KEY(CD_USUARIO)
);
/* FALTOU ADD CONSTRAINT UNIQUE NO EMAIL E CPF */
ALTER TABLE TB_USUARIO ADD CONSTRAINT EMAIL_USER_UNICO UNIQUE(NM_EMAIL);
ALTER TABLE TB_USUARIO ADD CONSTRAINT CPF_USER_UNICO UNIQUE(CD_CPF);

CREATE TABLE TB_PALESTRANTE(
CD_PALESTRANTE INT AUTO_INCREMENT,
NM_PALESTRANTE VARCHAR(45) NOT NULL,
CD_CPF VARCHAR(11) NOT NULL,
CONSTRAINT CPF_PALEST_UNICO UNIQUE(CD_CPF),
CD_RG VARCHAR(9) NOT NULL,
NM_EMAIL VARCHAR(100) NOT NULL,
CONSTRAINT EMAIL_PALEST_UNICO UNIQUE(NM_EMAIL),
DT_NASCIMENTO DATE NOT NULL,
DS_PALESTRANTE LONGTEXT,
ID_ADMINISTRADOR INT NOT NULL,
PRIMARY KEY(CD_PALESTRANTE),
CONSTRAINT ADM_PALEST_FK
FOREIGN KEY(ID_ADMINISTRADOR) REFERENCES 
TB_ADMINISTRADOR(CD_ADMINISTRADOR)
ON UPDATE CASCADE
ON DELETE CASCADE,
DT_CADASTRO TIMESTAMP NOT NULL
DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE TB_ESTADO(
CD_ESTADO INT AUTO_INCREMENT,
NM_ESTADO VARCHAR(45) NOT NULL UNIQUE,
PRIMARY KEY(CD_ESTADO)
);

CREATE TABLE TB_CIDADE(
CD_CIDADE INT AUTO_INCREMENT,
NM_CIDADE VARCHAR(45) NOT NULL,
ID_ESTADO INT NOT NULL,
PRIMARY KEY(CD_CIDADE),
FOREIGN KEY(ID_ESTADO) REFERENCES TB_ESTADO(CD_ESTADO)
);

CREATE TABLE TB_CATEGORIA(
CD_CATEGORIA INT AUTO_INCREMENT PRIMARY KEY,
NM_CATEGORIA VARCHAR(45) NOT NULL UNIQUE,
DS_CATEGORIA LONGTEXT
);

CREATE TABLE TB_EVENTO(
CD_EVENTO INT AUTO_INCREMENT PRIMARY KEY,
NM_EVENTO VARCHAR(45) NOT NULL,
ID_CATEGORIA INT NOT NULL,
CONSTRAINT EVENT_CAT_FK 
FOREIGN KEY(ID_CATEGORIA) REFERENCES TB_CATEGORIA(CD_CATEGORIA)
ON UPDATE CASCADE ON DELETE CASCADE,
NM_ENDERECO VARCHAR(150) NOT NULL,
NR_ENDERECO VARCHAR(10) NOT NULL,
NM_COMPLEMENTO VARCHAR(100),
DS_PONTO_REFERENCIA LONGTEXT,
NM_BAIRRO VARCHAR(50) NOT NULL,
ID_CIDADE INT NOT NULL,
CONSTRAINT EVENT_CIDADE_FK
FOREIGN KEY(ID_CIDADE) REFERENCES TB_CIDADE(CD_CIDADE)
ON UPDATE CASCADE ON DELETE CASCADE,
DT_INICIO DATE NOT NULL,
HR_INICIO TIME NOT NULL,
DT_FINAL DATE,
HR_FINAL TIME NOT NULL,
DT_CADASTRO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP 
ON UPDATE CURRENT_TIMESTAMP,
ID_ADMINISTRADOR INT NOT NULL,
CONSTRAINT EVENT_ADM_FK 
FOREIGN KEY(ID_ADMINISTRADOR) REFERENCES TB_ADMINISTRADOR(CD_ADMINISTRADOR)
);

CREATE TABLE TB_EVENTO_ORGANIZACAO(
ID_EVENTO INT NOT NULL,
CONSTRAINT EVENT_FK
FOREIGN KEY(ID_EVENTO) REFERENCES TB_EVENTO(CD_EVENTO)
ON UPDATE CASCADE ON DELETE CASCADE,
ID_ORGANIZADOR INT NOT NULL,
CONSTRAINT EVENT_ORG_FK 
FOREIGN KEY(ID_ORGANIZADOR) REFERENCES TB_ORGANIZADOR(CD_ORGANIZADOR)
ON UPDATE CASCADE ON DELETE CASCADE,
ID_PATROCINADOR INT NOT NULL, 
CONSTRAINT EVENT_PAT_FK 
FOREIGN KEY(ID_PATROCINADOR) REFERENCES TB_PATROCINADOR(CD_PATROCINADOR)
);

CREATE TABLE TB_TIPO_EVENTO(
CD_TIPO_EVENTO INT AUTO_INCREMENT PRIMARY KEY,
NM_TIPO_EVENTO VARCHAR(45) NOT NULL,
DS_TIPO_EVENTO LONGTEXT NOT NULL,
ID_PALESTRANTE INT NOT NULL,
ID_EVENTO INT NOT NULL,
NM_LOCAL VARCHAR(45) NOT NULL,
DT_INICIO DATE NOT NULL,
HR_INICIO TIME NOT NULL,
DT_FINAL DATE,
HR_FINAL TIME NOT NULL,
QT_PARTICIPANTE INT NOT NULL
);
ALTER TABLE TB_TIPO_EVENTO ADD
CONSTRAINT EVENT_PALEST_FK
FOREIGN KEY(ID_PALESTRANTE) REFERENCES TB_PALESTRANTE(CD_PALESTRANTE)
ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE TB_TIPO_EVENTO ADD
CONSTRAINT EVENT_TIPO_FK
FOREIGN KEY(ID_EVENTO) REFERENCES TB_EVENTO(CD_EVENTO)
ON UPDATE CASCADE ON DELETE CASCADE;

CREATE TABLE TB_INSCRICAO(
CD_INSCRICAO INT AUTO_INCREMENT PRIMARY KEY,
ID_TIPO INT NOT NULL,
ID_USUARIO INT NOT NULL,
DT_INSCRICAO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
ST_INSCRICAO CHAR(1) NOT NULL DEFAULT 'F'
);

ALTER TABLE TB_INSCRICAO ADD
FOREIGN KEY(ID_TIPO) REFERENCES TB_TIPO_EVENTO(CD_TIPO_EVENTO)
ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE TB_INSCRICAO ADD
CONSTRAINT INSC_USER_FK 
FOREIGN KEY(ID_USUARIO) REFERENCES TB_USUARIO(CD_USUARIO)
ON UPDATE CASCADE ON DELETE CASCADE;